### ISSUE TITLE
Include directory not found

### ISSUE THREAD

**Issue by GPrathap** [ethz-asl/tensorflow_catkin#1]
```
/apollo/modules/additional_ros_packages/object_tracker/src/example.cpp:1:44: fatal error: tensorflow/core/public/session.h: No such file or directory
 #include <tensorflow/core/public/session.h>
                                            ^
compilation terminated.

```
I was able to build the  tensorflow_catkin but I when try to work as external library it is unable to find the the header files. Can you comment what will the possible issues?

I use Ubuntu 14.04 and CUDA 8

**Comment by sarlinpe** [comment]
What do you exactly mean by "external library"? Are you building this package and your application into the same Catkin workspace?

**Comment by GPrathap** [comment]
Heyy sorry not reply on this. We use Apollo (https://github.com/ApolloAuto/apollo) where they have own custom version of ROS. It is required to manually copy "include, lib, share" directory into ROS installation directory.  That is why I did get this error, I after I copied those files everything works well. 

Thank you for this contribution and you can close this issue.:)

**Comment by sarlinpe** [comment]
Great, glad you find this useful.
